// Code generated by protoc-gen-go.
// source: storage/storage.proto
// DO NOT EDIT!

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	storage/storage.proto

It has these top-level messages:
	ProtoPartition
	ProtoStore
*/
package storage

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoPartition struct {
	SegmentKeys      []uint64 `protobuf:"varint,1,rep,packed" json:"SegmentKeys,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoPartition) Reset()         { *m = ProtoPartition{} }
func (m *ProtoPartition) String() string { return proto.CompactTextString(m) }
func (*ProtoPartition) ProtoMessage()    {}

func (m *ProtoPartition) GetSegmentKeys() []uint64 {
	if m != nil {
		return m.SegmentKeys
	}
	return nil
}

type ProtoStore struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	Codec            *string `protobuf:"bytes,2,req" json:"Codec,omitempty"`
	Version          *int32  `protobuf:"varint,3,req" json:"Version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoStore) Reset()         { *m = ProtoStore{} }
func (m *ProtoStore) String() string { return proto.CompactTextString(m) }
func (*ProtoStore) ProtoMessage()    {}

func (m *ProtoStore) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoStore) GetCodec() string {
	if m != nil && m.Codec != nil {
		return *m.Codec
	}
	return ""
}

func (m *ProtoStore) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func init() {
}
