// Code generated by protoc-gen-go.
// source: transactor/index.proto
// DO NOT EDIT!

/*
Package transactor is a generated protocol buffer package.

It is generated from these files:
	transactor/index.proto

It has these top-level messages:
	ProtoIndex
	ProtoIndexedFact
*/
package transactor

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoIndex struct {
	Domains          []*ProtoIndexKeyValue   `protobuf:"bytes,1,rep" json:"Domains,omitempty"`
	Entities         []*ProtoIndexKeyValue   `protobuf:"bytes,2,rep" json:"Entities,omitempty"`
	Attributes       []*ProtoIndexKeyValue   `protobuf:"bytes,3,rep" json:"Attributes,omitempty"`
	Values           []*ProtoIndexKeyValue   `protobuf:"bytes,4,rep" json:"Values,omitempty"`
	Times            *ProtoIndexKeyValueTime `protobuf:"bytes,5,req" json:"Times,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ProtoIndex) Reset()         { *m = ProtoIndex{} }
func (m *ProtoIndex) String() string { return proto.CompactTextString(m) }
func (*ProtoIndex) ProtoMessage()    {}

func (m *ProtoIndex) GetDomains() []*ProtoIndexKeyValue {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *ProtoIndex) GetEntities() []*ProtoIndexKeyValue {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *ProtoIndex) GetAttributes() []*ProtoIndexKeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ProtoIndex) GetValues() []*ProtoIndexKeyValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ProtoIndex) GetTimes() *ProtoIndexKeyValueTime {
	if m != nil {
		return m.Times
	}
	return nil
}

type ProtoIndexKeyValue struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *int32  `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoIndexKeyValue) Reset()         { *m = ProtoIndexKeyValue{} }
func (m *ProtoIndexKeyValue) String() string { return proto.CompactTextString(m) }
func (*ProtoIndexKeyValue) ProtoMessage()    {}

func (m *ProtoIndexKeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProtoIndexKeyValue) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ProtoIndexKeyValueTime struct {
	Key              *int64 `protobuf:"varint,1,req,name=key" json:"key,omitempty"`
	Value            *int32 `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoIndexKeyValueTime) Reset()         { *m = ProtoIndexKeyValueTime{} }
func (m *ProtoIndexKeyValueTime) String() string { return proto.CompactTextString(m) }
func (*ProtoIndexKeyValueTime) ProtoMessage()    {}

func (m *ProtoIndexKeyValueTime) GetKey() int64 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *ProtoIndexKeyValueTime) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ProtoIndexedFact struct {
	Domain           *int32 `protobuf:"varint,1,req" json:"Domain,omitempty"`
	Time             *int32 `protobuf:"varint,2,req" json:"Time,omitempty"`
	Operation        *bool  `protobuf:"varint,3,req" json:"Operation,omitempty"`
	EntityDomain     *int32 `protobuf:"varint,4,req" json:"EntityDomain,omitempty"`
	Entity           *int32 `protobuf:"varint,5,req" json:"Entity,omitempty"`
	AttributeDomain  *int32 `protobuf:"varint,6,req" json:"AttributeDomain,omitempty"`
	Attribute        *int32 `protobuf:"varint,7,req" json:"Attribute,omitempty"`
	ValueDomain      *int32 `protobuf:"varint,8,req" json:"ValueDomain,omitempty"`
	Value            *int32 `protobuf:"varint,9,req" json:"Value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoIndexedFact) Reset()         { *m = ProtoIndexedFact{} }
func (m *ProtoIndexedFact) String() string { return proto.CompactTextString(m) }
func (*ProtoIndexedFact) ProtoMessage()    {}

func (m *ProtoIndexedFact) GetDomain() int32 {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return 0
}

func (m *ProtoIndexedFact) GetTime() int32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *ProtoIndexedFact) GetOperation() bool {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return false
}

func (m *ProtoIndexedFact) GetEntityDomain() int32 {
	if m != nil && m.EntityDomain != nil {
		return *m.EntityDomain
	}
	return 0
}

func (m *ProtoIndexedFact) GetEntity() int32 {
	if m != nil && m.Entity != nil {
		return *m.Entity
	}
	return 0
}

func (m *ProtoIndexedFact) GetAttributeDomain() int32 {
	if m != nil && m.AttributeDomain != nil {
		return *m.AttributeDomain
	}
	return 0
}

func (m *ProtoIndexedFact) GetAttribute() int32 {
	if m != nil && m.Attribute != nil {
		return *m.Attribute
	}
	return 0
}

func (m *ProtoIndexedFact) GetValueDomain() int32 {
	if m != nil && m.ValueDomain != nil {
		return *m.ValueDomain
	}
	return 0
}

func (m *ProtoIndexedFact) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func init() {
}
